### ISSUE TITLE
Make XPM "Target" Configurable

### ISSUE THREAD

**Issue by Nivlong** [bkoopman/tri#10]
The Page TBB relies on the term "Staging" to generate the XPM markup.

As discussed in: [Tridion Reference Implementation - Experience Manager button does not show](http://tridion.stackexchange.com/q/7976/46), we talked about making this configurable. For example, the Target Type might be called "Preview" instead.

Bart also noted the XPM settings might change in the next release.

**Comment by bkoopman** [comment]
fixed in DXA 1.1 https://community.sdl.com/developers/tridion_developer/m/mediagallery/852
