### ISSUE TITLE
DD4TModelBuilder.GetCompLink(s) methods removed at some point

### ISSUE THREAD

**Issue by willprice76** [bkoopman/tri#11]
Although they are not needed with the models shipped with TRI, they are useful when you want to populate a full linked model object from a link field. See http://tridion.stackexchange.com/questions/8377/issue-with-getcomplink-in-the-tridion-reference-implementation for the fix.

**Comment by bkoopman** [comment]
fixed in DXA 1.1 https://community.sdl.com/developers/tridion_developer/m/mediagallery/852
