### ISSUE TITLE
No Generic Mapping of Multimedia Links

### ISSUE THREAD

**Issue by willprice76** [bkoopman/tri#15]
If you create new multimedia schemas and corresponding models, links to these in parent models do not get mapped. See http://tridion.stackexchange.com/questions/11142/adding-mapping-to-a-custom-image-model-in-tridion-reference-implementation for more information

**Comment by bkoopman** [comment]
fixed in DXA 1.1 https://community.sdl.com/developers/tridion_developer/m/mediagallery/852
